### ISSUE TITLE
init_sd_card fails at downloading image

### ISSUE THREAD

**Issue by denismaua** [duckietown/duckietown-shell-commands#329]
Hello,

  I have tried running its init_sd_card several times from a very good internet connection and every time the command halts when downloading the Jetson 2GB disk image at different %. Also, the download is very slow. Is there an alternative to it?

There is a similar question (not mine) on duckietown stack overflow forum: https://www.duckietown.org/questions/question/trouble-burning-sd-card

**Comment by jasonhu5** [comment]
@denismaua Have you managed to complete init_sd_card? By the way, the link to the StackOverflow page seems invalid. Low download speed might have something to do with internet setup or our server disruptions.

Since there are not a lot of reports on the download being stuck completely, we're not sure exactly how the problem could be reproduced. If you continue to experience the problem, feel free to reopen the issue.

**Comment by denismaua** [comment]
Hi Jason,

   I have managed to complete the download in two ways: I repeatedly tried to download until I eventually succeed, then I copied the file to the appropriate directory when burning a new image.
My guess is that there is some instability with the server. It would be good if the download could be made manually and/or that it could be resumed from where it halted.

Thanks anyway,
Denis

**Comment by jasonhu5** [comment]
Glad to hear it worked out. And thank you for the information and suggestion!
