### ISSUE TITLE
command not working

### ISSUE THREAD

**Issue by Tianchengbao** [duckietown/duckietown-shell-commands#330]
The command is stuck at step 11/59 and I cannot import duckietown.dtros.
![Screenshot from 2022-09-15 01-49-27](https://user-images.githubusercontent.com/93534222/190324574-e7e162e8-066a-44b5-acf4-6fbb12b926a2.png)

**Comment by jasonhu5** [comment]
For the first problem: command being stuck at step 11/59, there might be 2 reasons
- The base image is being pulled and it could take some time depending on your location and access to DockerHub
- The base image could not be pulled because the docker credentials have not been set. (see the orange prompt on top in the terminal)

For the second problem, `dtros` could not be imported in the IDE, that is normal. Because it's a module that comes with the base image, so before building, the IDE would not recognize the library. There could be 2 solutions:
- you can clone the `duckietown/dt-ros-commons` package and put it somewhere included for python path
- or you could try building an image and develop within an instance container (vscode could do that)

Feel free to reopen the issue if further problems is experienced with building, after you tried DockerHub mirrors and set your logins with the orange dts command.
